version: '3.9'

services:
  ${DOCKER_SERVICE_NAME}:
    container_name: ${DOCKER_SERVICE_NAME}
    image: centinel-api/${DOCKER_SERVICE_NAME}:latest
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - '/var/www/uploads:/uploads'
      - './logs:/app/logs'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    restart: always
    networks:
      - centinel-api-net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - centinel-api-net

networks:
  centinel-api-net:
    driver: bridge
